enum AuthErrorCode {
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
  REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED",
  REFRESH_TOKEN_REVOKED = "REFRESH_TOKEN_REVOKED",
  AUTH_TOKEN_MISSING = "AUTH_TOKEN_MISSING",
  INVALID_ACCESS_TOKEN = "INVALID_ACCESS_TOKEN",
}

export default AuthErrorCode;
