enum AuthErrorCode {
  AUTH_TOKEN_MISSING = "AUTH_TOKEN_MISSING",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
  INVALID_ACCESS_TOKEN = "INVALID_ACCESS_TOKEN",
  ACCESS_TOKEN_EXPIRED = "ACCESS_TOKEN_EXPIRED",
  REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED",
  REFRESH_TOKEN_REVOKED = "REFRESH_TOKEN_REVOKED",
  SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
  SESSION_ACCESS_DENIED = "SESSION_ACCESS_DENIED",
}

export default AuthErrorCode;
