enum ErrorCode {
  // User error code
  INVALID_REQUEST_BODY = "INVALID_REQUEST_BODY",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  MISSING_SESSION_ID = "MISSING_SESSION_ID",
  SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
  SESSION_EXPIRED = "SESSION_EXPIRED",
  IP_CHANGED = "IP_CHANGED",
  BROWSER_MISMATCH = "BROWSER_MISMATCH",
  INVALID_SESSION = "INVALID_SESSION",
  SESSION_REVOKED = "SESSION_REVOKED",

  // Resource error code
  RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS",

  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",

  INTERNAL_SERVER = "INTERNAL_SERVER",
  BAD_REQUEST = "BAD_REQUEST",
}

export default ErrorCode;
