enum ErrorCode {
  INVALID_REQUEST_BODY = "INVALID_REQUEST_BODY",

  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  INTERNAL_SERVER = "INTERNAL_SERVER",
  BAD_REQUEST = "BAD_REQUEST",
}

export default ErrorCode;
