enum ErrorCode {
  // Auth error code
  INVALID_REQUEST_BODY = "INVALID_REQUEST_BODY",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS",
  PASSWORD_TOO_SHORT = "PASSWORD_TOO_SHORT",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  MISSING_SESSION_ID = "MISSING_SESSION_ID",
  SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
  SESSION_EXPIRED = "SESSION_EXPIRED",
  IP_CHANGED = "IP_CHANGED",
  BROWSER_MISMATCH = "BROWSER_MISMATCH",
  EMAIL_NOT_FOUND = "EMAIL_NOT_FOUND",
  USERNAME_NOT_FOUND = "USERNAME_NOT_FOUND",
  INVALID_SESSION = "INVALID_SESSION",
  SESSION_REVOKED = "SESSION_REVOKED",

  // Profile error code
  PROFILE_ALREADY_EXISTS = "PROFILE_ALREADY_EXISTS",
  PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND",

  // Resource error code
  RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS",

  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",

  INTERNAL_SERVER = "INTERNAL_SERVER",
  BAD_REQUEST = "BAD_REQUEST",

  // Station error code
  STATION_NOT_FOUND = "STATION_NOT_FOUND",

  // Train Discovery error code
  SOURCE_DESTINATION_SAME = "SOURCE_DESTINATION_SAME",
}

export default ErrorCode;
